kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mintmaker-admin
  namespace: mintmaker
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mintmaker-admins
  namespace: mintmaker
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: konflux-mintmaker-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mintmaker-admin
